#!/usr/bin/env python3
"""
Simple audiobook HTTP server.
Serves MP3 files from a directory + podcast RSS feed + web player.
Usage: python audiobook_server.py <audiobook_dir> [--port 8765] [--title "Book Title"]
"""

import argparse
import email.utils
import http.server
import os
import re
import socketserver
import time
import urllib.parse
from pathlib import Path

# ── RSS feed ──────────────────────────────────────────────────────────────────

def make_rss(base_url: str, title: str, mp3_files: list[Path]) -> str:
    pub_date = email.utils.formatdate()
    items = []
    for i, f in enumerate(mp3_files):
        size = f.stat().st_size
        name = urllib.parse.quote(f.name)
        duration_secs = int(size * 8 / 64000)  # rough estimate at 64kbps
        h, m, s = duration_secs // 3600, (duration_secs % 3600) // 60, duration_secs % 60
        ep_title = f.stem.replace('_', ' ').replace('-', ' ')
        items.append(f"""
  <item>
    <title>{ep_title}</title>
    <enclosure url="{base_url}/files/{name}" length="{size}" type="audio/mpeg"/>
    <guid>{base_url}/files/{name}</guid>
    <pubDate>{pub_date}</pubDate>
    <itunes:duration>{h:02d}:{m:02d}:{s:02d}</itunes:duration>
    <itunes:episode>{i+1}</itunes:episode>
  </item>""")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title>{title}</title>
  <link>{base_url}</link>
  <description>Generated by NanoClaw Audiobook</description>
  <language>zh-CN</language>
  <pubDate>{pub_date}</pubDate>
  <itunes:category text="Books"/>
  {''.join(items)}
</channel>
</rss>"""


# ── HTML player ───────────────────────────────────────────────────────────────

def make_player(base_url: str, title: str, mp3_files: list[Path]) -> str:
    tracks = []
    for i, f in enumerate(mp3_files):
        name = urllib.parse.quote(f.name)
        label = f.stem.replace('_', ' ')
        tracks.append(f'  {{ title: "{label}", src: "{base_url}/files/{name}" }}')
    tracks_js = ',\n'.join(tracks)

    return f"""<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 600px;
         margin: 0 auto; padding: 20px; background: #1a1a2e; color: #eee; }}
  h1 {{ font-size: 1.2em; color: #e0aaff; }}
  audio {{ width: 100%; margin: 12px 0; }}
  .track {{ padding: 10px; margin: 4px 0; border-radius: 8px; cursor: pointer;
            background: #16213e; border: 1px solid #0f3460; }}
  .track:hover, .track.active {{ background: #533483; }}
  .track-title {{ font-size: 0.9em; }}
  #rss-link {{ color: #a78bfa; font-size: 0.85em; word-break: break-all; }}
  .speed-controls {{ display: flex; gap: 8px; flex-wrap: wrap; margin: 8px 0; }}
  .speed-btn {{ background: #16213e; border: 1px solid #0f3460; color: #eee;
                padding: 5px 10px; border-radius: 6px; cursor: pointer; font-size: 0.85em; }}
  .speed-btn.active {{ background: #533483; border-color: #a78bfa; }}
</style>
</head>
<body>
<h1>📖 {title}</h1>
<audio id="player" controls preload="none"></audio>
<div class="speed-controls" id="speed-controls"></div>
<p>RSS feed for podcast apps: <a id="rss-link" href="{base_url}/feed.xml">{base_url}/feed.xml</a></p>
<div id="tracklist"></div>
<script>
const tracks = [
{tracks_js}
];
const player = document.getElementById('player');
const list = document.getElementById('tracklist');
let current = 0;

tracks.forEach((t, i) => {{
  const d = document.createElement('div');
  d.className = 'track';
  d.innerHTML = '<span class="track-title">' + (i+1) + '. ' + t.title + '</span>';
  d.onclick = () => play(i);
  list.appendChild(d);
}});

function play(i) {{
  current = i;
  document.querySelectorAll('.track').forEach((el, j) => el.classList.toggle('active', j===i));
  player.src = tracks[i].src;
  player.play();
}}

player.onended = () => {{ if (current + 1 < tracks.length) play(current + 1); }};

// Speed controls
const speeds = [0.7, 0.8, 0.9, 1.0, 1.2, 1.5, 2.0];
const speedDiv = document.getElementById('speed-controls');
let currentSpeed = 1.0;
speeds.forEach(s => {{
  const btn = document.createElement('button');
  btn.className = 'speed-btn' + (s === 1.0 ? ' active' : '');
  btn.textContent = s + '×';
  btn.onclick = () => {{
    currentSpeed = s;
    player.playbackRate = s;
    document.querySelectorAll('.speed-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
  }};
  speedDiv.appendChild(btn);
}});
player.onplay = () => {{ player.playbackRate = currentSpeed; }};

if (tracks.length > 0) play(0);
</script>
</body>
</html>"""


# ── HTTP server ───────────────────────────────────────────────────────────────

class Handler(http.server.BaseHTTPRequestHandler):
    audiobook_dir: Path
    title: str
    base_url: str

    def log_message(self, fmt, *args):
        pass  # suppress default logging

    def _get_mp3s(self):
        return sorted(self.audiobook_dir.glob('*.mp3'))

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        mp3s = self._get_mp3s()

        if path in ('/', '/index.html'):
            body = make_player(self.base_url, self.title, mp3s).encode()
            self.send_response(200)
            self.send_header('Content-Type', 'text/html; charset=utf-8')
            self.send_header('Content-Length', len(body))
            self.end_headers()
            self.wfile.write(body)

        elif path == '/feed.xml':
            body = make_rss(self.base_url, self.title, mp3s).encode()
            self.send_response(200)
            self.send_header('Content-Type', 'application/rss+xml; charset=utf-8')
            self.send_header('Content-Length', len(body))
            self.end_headers()
            self.wfile.write(body)

        elif path.startswith('/files/'):
            fname = urllib.parse.unquote(path[7:])
            fpath = self.audiobook_dir / fname
            if fpath.exists() and fpath.suffix == '.mp3':
                size = fpath.stat().st_size
                self.send_response(200)
                self.send_header('Content-Type', 'audio/mpeg')
                self.send_header('Content-Length', size)
                self.send_header('Accept-Ranges', 'bytes')
                self.end_headers()
                with open(fpath, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_response(404)
                self.end_headers()
        else:
            self.send_response(404)
            self.end_headers()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('dir', help='Directory containing MP3 files')
    parser.add_argument('--port', type=int, default=8765)
    parser.add_argument('--title', default='Audiobook')
    parser.add_argument('--base-url', default='', help='Public base URL (set by cloudflared)')
    args = parser.parse_args()

    audiobook_dir = Path(args.dir).resolve()
    base_url = args.base_url.rstrip('/') or f'http://localhost:{args.port}'

    Handler.audiobook_dir = audiobook_dir
    Handler.title = args.title
    Handler.base_url = base_url

    mp3s = sorted(audiobook_dir.glob('*.mp3'))
    print(f'Serving {len(mp3s)} MP3(s) from {audiobook_dir}')
    print(f'Web player: {base_url}/')
    print(f'RSS feed:   {base_url}/feed.xml')

    with socketserver.TCPServer(('', args.port), Handler) as httpd:
        httpd.serve_forever()


if __name__ == '__main__':
    main()
