#!/usr/bin/env python3
"""
Upload an MP3 audiobook chapter to YouTube as an unlisted video.
Converts audio to MP4 (dark background) then uploads via YouTube Data API v3.

Usage:
  python youtube_upload.py <mp3_file> --title "..." --playlist "..." [--credentials creds.json]
  python youtube_upload.py --auth   # first-time auth only
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

SCOPES = ['https://www.googleapis.com/auth/youtube.upload',
          'https://www.googleapis.com/auth/youtube']
TOKEN_FILE = Path('/home/binxu/.config/nanoclaw/youtube_token.json')
CLIENT_SECRETS_FILE = Path('/home/binxu/.config/nanoclaw/youtube_client_secret.json')
FFMPEG = '/home/binxu/miniforge3/envs/research/bin/ffmpeg'


def get_credentials():
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from google_auth_oauthlib.flow import InstalledAppFlow

    creds = None
    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not CLIENT_SECRETS_FILE.exists():
                print(f"ERROR: Client secrets not found at {CLIENT_SECRETS_FILE}")
                sys.exit(1)
            flow = InstalledAppFlow.from_client_secrets_file(str(CLIENT_SECRETS_FILE), SCOPES)
            # Local server flow — WSL2 localhost is shared with Windows browser
            creds = flow.run_local_server(port=8585, open_browser=False,
                                          success_message='Auth complete! You can close this tab.')

        TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
        TOKEN_FILE.write_text(creds.to_json())
        print("Credentials saved.")

    return creds


def mp3_to_mp4(mp3_path: str, mp4_path: str) -> None:
    """Convert MP3 to MP4 with a dark background (minimal encoding, ultrafast)."""
    subprocess.run([
        FFMPEG, '-y',
        '-f', 'lavfi', '-i', 'color=c=0x1a1a2e:size=1280x720:rate=1',
        '-i', mp3_path,
        '-shortest',
        '-c:v', 'libx264', '-preset', 'ultrafast', '-tune', 'stillimage', '-crf', '28',
        '-c:a', 'aac', '-b:a', '128k',
        mp4_path
    ], check=True, capture_output=True)


def upload_video(creds, mp4_path: str, title: str, description: str,
                 playlist_id: str = None) -> str:
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload

    youtube = build('youtube', 'v3', credentials=creds)

    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': ['audiobook', 'TTS', 'VoxCPM'],
            'categoryId': '22',  # People & Blogs
        },
        'status': {
            'privacyStatus': 'unlisted',
            'selfDeclaredMadeForKids': False,
        }
    }

    media = MediaFileUpload(mp4_path, mimetype='video/mp4', resumable=True, chunksize=5*1024*1024)
    request = youtube.videos().insert(part='snippet,status', body=body, media_body=media)

    print(f"Uploading: {title}")
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"  {int(status.progress() * 100)}%", end='\r')

    video_id = response['id']
    url = f"https://youtu.be/{video_id}"
    print(f"\nUploaded: {url}")

    if playlist_id:
        youtube.playlistItems().insert(
            part='snippet',
            body={'snippet': {
                'playlistId': playlist_id,
                'resourceId': {'kind': 'youtube#video', 'videoId': video_id}
            }}
        ).execute()
        print(f"Added to playlist: {playlist_id}")

    return url


def create_playlist(creds, title: str, description: str) -> str:
    from googleapiclient.discovery import build
    youtube = build('youtube', 'v3', credentials=creds)
    result = youtube.playlists().insert(
        part='snippet,status',
        body={
            'snippet': {'title': title, 'description': description},
            'status': {'privacyStatus': 'unlisted'}
        }
    ).execute()
    playlist_id = result['id']
    print(f"Created playlist: https://youtube.com/playlist?list={playlist_id}")
    return playlist_id


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('mp3', nargs='?', help='MP3 file to upload')
    parser.add_argument('--title', default='')
    parser.add_argument('--description', default='Generated by NanoClaw Audiobook')
    parser.add_argument('--playlist-id', default='', help='YouTube playlist ID to add to')
    parser.add_argument('--auth', action='store_true', help='Run OAuth flow only')
    parser.add_argument('--create-playlist', metavar='TITLE', help='Create a new unlisted playlist')
    args = parser.parse_args()

    creds = get_credentials()

    if args.auth:
        print("Authentication successful!")
        return

    if args.create_playlist:
        playlist_id = create_playlist(creds, args.create_playlist, args.description)
        print(f"Playlist ID: {playlist_id}")
        return

    if not args.mp3:
        parser.error("Provide an MP3 file to upload")

    mp3_path = args.mp3
    title = args.title or Path(mp3_path).stem

    with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as f:
        mp4_path = f.name

    try:
        print(f"Converting {mp3_path} → MP4...")
        mp3_to_mp4(mp3_path, mp4_path)
        url = upload_video(creds, mp4_path, title, args.description,
                           args.playlist_id or None)
        print(url)
    finally:
        os.unlink(mp4_path)


if __name__ == '__main__':
    main()
